#define GLM_ENABLE_EXPERIMENTAL
#include<Windows.h>
#include<glm/glm.hpp>
#include<glm/gtc/matrix_transform.hpp>
#include<glm/gtc/type_ptr.hpp>
#include<glm/gtx/rotate_normalized_axis.hpp>
#include<iostream>
#include<glad/gl.h>
#include<GLFW/glfw3.h>
#include<chrono>
#include<numeric>
#include<vector>
#include<string>
#include<fstream>
#include<sstream>
#include<ostream>
#include<filesystem>
#include<thread>
#include<random>
#include<conio.h>
#include"assimp/Importer.hpp"
#include"assimp/scene.h"
#include"assimp/postprocess.h"
#include<map>